// DISPLAY:
#define DISPLAY_HEIGHT 48
#define DISPLAY_WIDTH 84

// FONT:
#define ROWS_PER_CHAR 8
#define COLUMNS_PER_CHAR 5

// METHOD:
#define CONTR_LEAST_VALUE 128
#define TEMP_LEAST_VALUE 4
#define NEW_LINE 0x0a

// MAIN:
#define TOTAL_ROWS (DISPLAY_HEIGHT / ROWS_PER_CHAR)
#define TOTAL_BITS (DISPLAY_WIDTH * TOTAL_ROWS)

// INSTRUCTION:
#define EXTENDED_IN 0x21
#define BASIC_IN 0x20